name: Python Greetings CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Force stop PM2 and Python before install
        shell: powershell
        run: |
          echo "Stopping ALL PM2 apps..."
          try {
            pm2 delete all
          } catch {
            Write-Host "No PM2 apps running"
          }
      
          echo "Killing Python processes..."
          try {
            Stop-Process -Name python -Force
          } catch {
            Write-Host "No python process running"
          }

  
      - name: Prepare all required actions
        uses: actions/checkout@v4
  
      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
  
      - name: Install Python dependencies
        uses: ./.github/actions/install-deps
        with:
          working-dir: greetings


  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - uses: ./.github/actions/deploy
        with:
          environment: dev
          port: 7001


  tests-on-dev:
    needs: deploy-to-dev
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - name: Restart PM2 before tests
        shell: powershell
        working-directory: greetings
        run: |
          echo "Restarting app for dev..."
          $env:PORT=7001
          pm2 start app.py --name greetings-app-dev --interpreter python
          Start-Sleep -Seconds 5
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework
      - uses: ./.github/actions/test
        with:
          working-dir: test-framework
          test-env: greetings_dev
          
      - name: Stop app after tests
        shell: powershell
        working-directory: greetings
        run: |
          echo "Stopping greetings-app-dev..."
          try {
            pm2 delete greetings-app-dev
          } catch {
            Write-Host "No PM2 app to stop"
          }
  
          echo "Killing python..."
          try {
            Stop-Process -Name python -Force
          } catch {
            Write-Host "No python to kill"
          }


  deploy-to-staging:
    needs: tests-on-dev
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - uses: ./.github/actions/deploy
        with:
          environment: staging
          port: 7002


  tests-on-staging:
    needs: deploy-to-staging
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - name: Restart PM2 before tests
        shell: powershell
        working-directory: greetings
        run: |
          echo "Restarting app for staging..."
          $env:PORT=7002
          pm2 start app.py --name greetings-app-staging --interpreter python
          Start-Sleep -Seconds 5
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework
      - uses: ./.github/actions/test
        with:
          working-dir: test-framework
          test-env: greetings_stg

  deploy-to-preprod:
    needs: tests-on-staging
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - uses: ./.github/actions/deploy
        with:
          environment: preprod
          port: 7003


  tests-on-preprod:
    needs: deploy-to-preprod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - name: Restart PM2 before tests
        shell: powershell
        working-directory: greetings
        run: |
          echo "Restarting app for preprod..."
          $env:PORT=7003
          pm2 start app.py --name greetings-app-preprod --interpreter python
          Start-Sleep -Seconds 5
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework
      - uses: ./.github/actions/test
        with:
          working-dir: test-framework
          test-env: greetings_preprod

  deploy-to-prod:
    needs: tests-on-preprod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - uses: ./.github/actions/deploy
        with:
          environment: prod
          port: 7004


  tests-on-prod:
    needs: deploy-to-prod
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: greetings
      - name: Restart PM2 before tests
        shell: powershell
        working-directory: greetings
        run: |
          echo "Restarting app for prod..."
          $env:PORT=7004
          pm2 start app.py --name greetings-app-prod --interpreter python
          Start-Sleep -Seconds 5
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: test-framework
      - uses: ./.github/actions/test
        with:
          working-dir: test-framework
          test-env: greetings_prod
